// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOHriLznSkgu_KiPZ3iIva6359FO8zif8',
    appId: '1:529227089299:web:ca5483ffd0fbe070345466',
    messagingSenderId: '529227089299',
    projectId: 'elcards-bd778',
    authDomain: 'elcards-bd778.firebaseapp.com',
    storageBucket: 'elcards-bd778.appspot.com',
    measurementId: 'G-P1Q469VQ8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjvR1erUKdoYVwYWL1AQXopIXM4MZEnlo',
    appId: '1:529227089299:android:a1930287ea097254345466',
    messagingSenderId: '529227089299',
    projectId: 'elcards-bd778',
    storageBucket: 'elcards-bd778.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsqBbqCtJ-QfQvfurRQJWLj0AiH-ZbnSo',
    appId: '1:529227089299:ios:1931b2a09303fb60345466',
    messagingSenderId: '529227089299',
    projectId: 'elcards-bd778',
    storageBucket: 'elcards-bd778.appspot.com',
    iosBundleId: 'com.meister.elcards',
  );
}
